---
# tasks file for first-role

    - name: Install apache httpd
      apt:
        name: apache2
        state: latest
        #update_cache: yes


    - name: Copy files to remote
      copy:
        src: files/home.html
        dest: /var/www/html 
